package com.shidun.model;

import java.io.Serializable;
import java.util.Date;

public class Code implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.issue
     *
     * @mbggenerated
     */
    private String issue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.lottery
     *
     * @mbggenerated
     */
    private String lottery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table code
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.id
     *
     * @return the value of code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.id
     *
     * @param id the value for code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.issue
     *
     * @return the value of code.issue
     *
     * @mbggenerated
     */
    public String getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.issue
     *
     * @param issue the value for code.issue
     *
     * @mbggenerated
     */
    public void setIssue(String issue) {
        this.issue = issue == null ? null : issue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code
     *
     * @return the value of code.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code
     *
     * @param code the value for code.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.create_time
     *
     * @return the value of code.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.create_time
     *
     * @param createTime the value for code.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.lottery
     *
     * @return the value of code.lottery
     *
     * @mbggenerated
     */
    public String getLottery() {
        return lottery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.lottery
     *
     * @param lottery the value for code.lottery
     *
     * @mbggenerated
     */
    public void setLottery(String lottery) {
        this.lottery = lottery == null ? null : lottery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", issue=").append(issue);
        sb.append(", code=").append(code);
        sb.append(", createTime=").append(createTime);
        sb.append(", lottery=").append(lottery);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}