package com.shidun.dao;

import com.shidun.model.PhoneNum;
import com.shidun.model.PhoneNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhoneNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    int countByExample(PhoneNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    int deleteByExample(PhoneNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    int insert(PhoneNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    int insertSelective(PhoneNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    List<PhoneNum> selectByExample(PhoneNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    PhoneNum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PhoneNum record, @Param("example") PhoneNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PhoneNum record, @Param("example") PhoneNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhoneNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_num
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhoneNum record);
}