package com.shidun.dao;

import com.shidun.model.UserTab;
import com.shidun.model.UserTabExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface UserTabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    int countByExample(UserTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    int deleteByExample(UserTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    int insert(UserTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    int insertSelective(UserTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    List<UserTab> selectByExample(UserTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    UserTab selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserTab record, @Param("example") UserTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserTab record, @Param("example") UserTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tab
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserTab record);
}